# These are supported funding model platforms

github: [Promethium]
patreon: promethium
open_collective: promethium
ko_fi: promethium
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: promethium
issuehunt: promethium
otechie: promethium
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
